apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnettest-deployment
  labels:
    app: dotnettest-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnettest
  template:
    metadata:
      labels:
        app: dotnettest
    spec:
      containers:
      - name: dotnettest
        image: mccreeshtestregistry.azurecr.io/dotnettest:v2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dotnettest-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: dotnettest